---
abstract: 'Alien package for the ZeroMQ library'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  ExtUtils::MakeMaker: '6.52'
  Test2::V0: '0'
  Test::Alien: '0'
  perl: '5.006'
configure_requires:
  Alien::Build: '0.32'
  Alien::Build::MM: '0.32'
  Alien::Build::Plugin::Gather::Dino: '0'
  ExtUtils::MakeMaker: '6.52'
  perl: '5.006'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-ZMQ-latest
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  Alien::Base: '0.038'
  Alien::Role::Dino: '0'
  Role::Tiny::With: '0'
  base: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/zmughal-CPAN/p5-Alien-ZMQ-latest
  repository: https://github.com/zmughal-CPAN/p5-Alien-ZMQ-latest.git
version: '0.006'
x_alienfile:
  generated_by: 'Dist::Zilla::Plugin::AlienBuild version 0.32'
  requires:
    share:
      Archive::Tar: '0'
      Config: '0'
      File::Which: '0'
      HTTP::Tiny: '0.044'
      IO::Socket::SSL: '1.56'
      IO::Zlib: '0'
      Mojo::DOM: '0'
      Mojolicious: '7.00'
      Net::SSLeay: '1.49'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_generated_by_perl: v5.26.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
