name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: "${{ matrix.os }} (alien_install_type: ${{ matrix.alien_install_type }}) (build_config_pref: ${{ matrix.build_config_pref }}) ${{ matrix.joblabel }}"
    runs-on: ${{ matrix.os }}
    env:
      ORBITAL_COVERAGE:    ${{ matrix.coverage }}
      ALIEN_INSTALL_TYPE:  ${{ matrix.alien_install_type }}
      ALIEN_ZMQ_LATEST_BUILD_CONFIG: ${{ matrix.build_config_pref }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        coverage: ['']
        alien_install_type: [ 'share', 'system' ]
        build_config_pref: ['']
        include:
          - os: 'ubuntu-latest'
            coverage: coveralls
            joblabel: '(Coverage)'
          - os: 'ubuntu-latest'
            alien_install_type: 'share'
            build_config_pref: 'autoconf'
          - os: 'ubuntu-latest'
            alien_install_type: 'share'
            build_config_pref: 'cmake'

    steps:
      - uses: actions/checkout@v3

      - name: Cache Orbital
        uses: actions/cache@v3
        env:
          cache-name: cache-orbital
        with:
          path: |
            ~/.orbital/extlib
            ~/.orbital/_orbital/author-local
            ~/.orbital/local
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.coverage }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.coverage }}-

      - name: Set up Orbital Transfer
        shell: bash
        run: |
          eval "$(curl https://raw.githubusercontent.com/orbital-transfer/launch-site/master/script/ci/github-actions-orbital.sh)"
      - name: Use Orbital Transfer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          perl -S orbitalism bootstrap auto
          perl -S orbitalism
          perl -S orbitalism test
